import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

let texto=fs.readFileSync(new URL('./cuenta-progreso.js',import.meta.url),'utf8');
const mutantes={
  reversion:['for(const [k,v] of Object.entries(antes))escribir(k,v);','void antes;'],
  guardia:['if(cambioExterno||marca()!==esperado||ajeno){','if(false){'],
  alias:['const origen=vinculo?.cuentaId?canonica:aliases.find(k=>leer(k)!==null)||actual;','const origen=aliases.find(k=>leer(k)!==null)||actual;'],
  lease:["if(diario.autor&&diario.autor!==autor&&Number.isFinite(diario.iniciada)&&reloj()-diario.iniciada<5000)throw fallo('PROGRESO_OCUPADO');",''],
  borrador:['campanaBorrador=null;','void 0;'],
};
if(process.env.CAOZ_SABOTAJE_PROGRESO&&process.env.CAOZ_SABOTAJE_PROGRESO!=='borrador'){const [antes,despues]=mutantes[process.env.CAOZ_SABOTAJE_PROGRESO];assert.ok(texto.includes(antes));texto=texto.replace(antes,despues);}
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const plano=v=>JSON.parse(JSON.stringify(v));
class Almacen {
  constructor(){this.m=new Map();this.escrituras=0;this.fallarEn=0;this.persistente=false;this.bloqueado=false;}
  getItem(k){if(this.bloqueado)throw Error('Bloqueado');return this.m.get(k)??null;}
  mutar(){this.escrituras++;if(this.fallarEn&&this.escrituras>=this.fallarEn){if(!this.persistente)this.fallarEn=0;throw Error('Cuota');}}
  setItem(k,v){this.mutar();this.m.set(k,String(v));} removeItem(k){this.mutar();this.m.delete(k);}
}
function entorno({storage=new Almacen(),ruta='/movil.html',host='juego.caozcontodo.com',reloj=Date.now}={}){
  const eventos=new EventTarget(),ctx=vm.createContext({crypto:webcrypto,TextEncoder,setInterval,clearInterval,CustomEvent,JSON,EventTarget,Storage:Almacen,location:{pathname:ruta,hostname:host,search:''},URLSearchParams,localStorage:storage});
  ctx.window=ctx;ctx.addEventListener=eventos.addEventListener.bind(eventos);ctx.dispatchEvent=eventos.dispatchEvent.bind(eventos);
  vm.runInContext(texto,ctx);const api=ctx.CAOZ_CUENTA_PROGRESO,p=api.crear({storage,ruta,hostname:host,eventos,intervalo:0,reloj});return {api,p,storage,eventos,ctx};
}
function ejemplo(){return {formato:'caoz.progreso',version:1,entorno:'produccion',datos:{
  campana:{version:1,id:'campana_unica',lider:'fender',etapa:5,personaje:{nombre:'Ari',color:'verde'},mesaPendiente:4,sobresPendientes:['antes']},
  borrador:{personaje:{nombre:'Ari',equipo:'libro'},lider:'fender'},logros:{version:1,mazos:{adreida:{nombre:'Nombre histórico',fecha:100}},ganador:null},
  coleccion:{version:1,revision:13,cantidades:{tal:{normal:1,foil:0,dorado:1}},desbloqueos:{tal:['foil','dorado']},selecciones:{tal:'dorado'},sobres:4,sobresVersion:2,sobresGuardados:{trucos:2},recompensasPorElegir:[{id:'premio',cantidad:2}],campanasPremiadas:['campana1'],domosPremiados:['domo1'],pendiente:{id:'ya_sorteado',cartas:[{id:'tal',acabado:'foil',nueva:false},{id:'rey',acabado:'normal',nueva:false},{id:'machete',acabado:'normal',nueva:true},{id:'armadura',acabado:'foil',nueva:true},{id:'eric',acabado:'normal',nueva:false}]}},
  premiosDomo:['domo_sin_acuse'],records:{lideres:{fender:{ganadas:4}},partidas:9},nombre:'Ari Online'}};}
function poblar(s,snapshot=ejemplo(),clave='caoz.coleccion.v1.produccion.raiz'){
  const claves={campana:'caoz.campana.v1',borrador:'caoz.campana.v1.creador',logros:'caoz.campana.logros.v1',coleccion:clave,premiosDomo:clave+'.domo-pendientes',records:'caoz_records_v1',nombre:'caoz_nombre'};
  for(const [k,v] of Object.entries(snapshot.datos))if(v!==null)s.setItem(claves[k],k==='nombre'?v:JSON.stringify(v));
}
let total=0;async function prueba(nombre,fn){await fn();total++;console.log('✓ '+nombre);}
await prueba('Captura campaña, recibos, canjes y las cinco cartas ya sorteadas sin alterarlos',()=>{const {p,storage}=entorno();poblar(storage);assert.deepEqual(plano(p.capturar()),ejemplo());});
await prueba('Excluye preferencias, estudios, simulaciones y otro entorno',()=>{const {p,storage}=entorno();for(const k of ['caoz.sonido.v1','claveEstudio','caoz.campana.logros.v1.simulados','caoz.coleccion.v1.beta.raiz'])storage.setItem(k,'secreto');assert.equal(p.capturar(),null);});
await prueba('El deseo nunca sale del dispositivo, ni cambia su original',()=>{const {p,storage}=entorno();const s=ejemplo();s.datos.campana.borradorDeseo='Mi texto privado';s.datos.campana.deseo={texto:'Otro secreto'};poblar(storage,s);const capturado=p.capturar();assert.equal(JSON.stringify(capturado).includes('secreto'),false);assert.equal(JSON.stringify(capturado).includes('privado'),false);assert.equal(JSON.parse(storage.getItem('caoz.campana.v1')).borradorDeseo,'Mi texto privado');});
await prueba('Un dato corrupto o almacenamiento bloqueado nunca se convierte en progreso vacío',()=>{const {p,storage}=entorno();storage.setItem('caoz.campana.v1','{roto');assert.throws(()=>p.capturar(),{codigo:'PROGRESO_DANADO'});storage.bloqueado=true;assert.throws(()=>p.capturar(),{codigo:'ALMACENAMIENTO'});});
await prueba('La ruta móvil limpia recupera el alias raíz si no tenía inventario',()=>{const {p,storage}=entorno({ruta:'/movil'});poblar(storage);assert.deepEqual(plano(p.capturar()),ejemplo());});
await prueba('Dos inventarios locales no se suman: gana el activo y los dos se respaldan',()=>{const {p,storage}=entorno({ruta:'/movil'});poblar(storage);const otro=ejemplo();otro.datos.coleccion.sobres=1;poblar(storage,otro,'caoz.coleccion.v1.produccion.movil');assert.equal(p.capturar().datos.coleccion.sobres,1);p.aplicar(ejemplo(),{cuentaId:A,revision:2});const b=p.respaldos().at(-1).datos;assert.equal(JSON.parse(b['caoz.coleccion.v1.produccion.raiz']).sobres,4);assert.equal(JSON.parse(b['caoz.coleccion.v1.produccion.movil']).sobres,1);});
await prueba('Aplicar conserva cantidades cero gastadas, pendientes y nombres históricos',()=>{const {p,storage}=entorno();const viejo=ejemplo();viejo.datos.coleccion.cantidades.tal.foil=5;poblar(storage,viejo);p.aplicar(ejemplo(),{cuentaId:A,revision:3});assert.deepEqual(plano(p.capturar()),ejemplo());assert.equal(p.vinculado().revision,3);assert.deepEqual(JSON.parse(storage.getItem('caoz.coleccion.v1.produccion.movil')),ejemplo().datos.coleccion);});
await prueba('Importaciones nulas, de otro entorno o sin todos los campos no escriben nada',()=>{const {p,storage}=entorno();poblar(storage);const antes=[...storage.m];for(const s of [null,{...ejemplo(),entorno:'beta'},{...ejemplo(),datos:{coleccion:{}}}])assert.throws(()=>p.aplicar(s,{cuentaId:A,revision:1}));assert.deepEqual([...storage.m],antes);});
await prueba('Sin espacio para el respaldo no modifica el progreso existente',()=>{const {p,storage}=entorno();poblar(storage);const antes=[...storage.m];storage.fallarEn=storage.escrituras+1;assert.throws(()=>p.aplicar(ejemplo(),{cuentaId:A,revision:3}),{codigo:'ALMACENAMIENTO'});assert.deepEqual([...storage.m],antes);});
await prueba('Un fallo a mitad de importación restaura todo el inventario anterior',()=>{const {p,storage}=entorno();const anterior=ejemplo();anterior.datos.campana.etapa=2;anterior.datos.coleccion.sobres=9;poblar(storage,anterior);storage.fallarEn=storage.escrituras+5;assert.throws(()=>p.aplicar(ejemplo(),{cuentaId:A,revision:3}),{codigo:'ALMACENAMIENTO'});assert.deepEqual(plano(p.capturar()),anterior);assert.equal(p.vinculado(),null);});
await prueba('Si también falla la reversión, la siguiente carga recupera el diario íntegro',()=>{const {p,storage}=entorno();const anterior=ejemplo();anterior.datos.campana.etapa=1;poblar(storage,anterior);storage.fallarEn=storage.escrituras+5;storage.persistente=true;assert.throws(()=>p.aplicar(ejemplo(),{cuentaId:A,revision:3}));assert.ok([...storage.m.keys()].some(k=>k.endsWith('.transaccion')));storage.fallarEn=0;storage.persistente=false;assert.throws(()=>entorno({storage}),{codigo:'PROGRESO_OCUPADO'});const otra=entorno({storage,reloj:()=>Date.now()+6000}).p;assert.deepEqual(plano(otra.capturar()),anterior);assert.equal(otra.vinculado(),null);});
await prueba('Cerrar cuenta archiva su copia y evita regalarla al próximo usuario',()=>{const {p}=entorno();p.aplicar(ejemplo(),{cuentaId:A,revision:3});p.desvincular();assert.equal(p.capturar(),null);assert.equal(p.vinculado(),null);assert.deepEqual(plano(p.archivo(A).snapshot),ejemplo());assert.equal(p.archivo(B),null);});
await prueba('Un deseo local sólo se conserva al restaurar la misma campaña y cuenta',()=>{const {p,storage}=entorno();p.aplicar(ejemplo(),{cuentaId:A,revision:3});const c=JSON.parse(storage.getItem('caoz.campana.v1'));c.borradorDeseo='Sólo Ari';storage.setItem('caoz.campana.v1',JSON.stringify(c));p.aplicar(ejemplo(),{cuentaId:A,revision:4});assert.equal(JSON.parse(storage.getItem('caoz.campana.v1')).borradorDeseo,'Sólo Ari');p.aplicar(ejemplo(),{cuentaId:B,revision:1});assert.equal(JSON.parse(storage.getItem('caoz.campana.v1')).borradorDeseo,undefined);});
await prueba('El observador detecta cambios y errores sin sustituirlos por un reset',()=>{const {p,storage}=entorno();const eventos=[];const salir=p.observar((s,e)=>eventos.push([plano(s),e]));poblar(storage);p.revisar();assert.deepEqual(eventos[0][0],ejemplo());storage.bloqueado=true;p.revisar();assert.equal(eventos[1][1].codigo,'ALMACENAMIENTO');storage.bloqueado=false;salir();p.destruir();});
await prueba('Las vistas devueltas no mutan inventario ni respaldos',()=>{const {p}=entorno();p.aplicar(ejemplo(),{cuentaId:A,revision:1});const c=p.capturar();c.datos.coleccion.sobres=900;const v=p.vinculado();v.base.datos.coleccion.sobres=999;assert.equal(p.capturar().datos.coleccion.sobres,4);assert.equal(p.vinculado().base.datos.coleccion.sobres,4);});
await prueba('Vincular vacío exige un dispositivo vacío y no destruye progreso por omisión',()=>{const {p,storage}=entorno();poblar(storage);assert.throws(()=>p.vincularVacio({cuentaId:A,revision:0}),{codigo:'PROGRESO_EXISTENTE'});assert.equal(p.capturar().datos.coleccion.sobres,4);const e=entorno();e.p.vincularVacio({cuentaId:A,revision:0});assert.equal(e.p.vinculado().cuentaId,A);});
await prueba('El resumen no suma sobres pendientes dos veces ni cuenta la Normal inicial como Foil',()=>{const {api}=entorno();const s=ejemplo(),r=api.resumir(s);assert.equal(r.sobres,4);assert.equal(r.foils,0);assert.equal(r.doradas,1);assert.equal(r.rivales,5);assert.equal(r.personaje,'Ari');});
await prueba('Rutas GitHub beta conservan su ámbito y nunca toman el inventario producción',()=>{const {p,storage}=entorno({ruta:'/csm-game-guide/tcg-beta/movil.html',host:'rafarorr1.github.io'});storage.setItem('caoz.coleccion.v1.produccion.raiz',JSON.stringify(ejemplo().datos.coleccion));assert.equal(p.capturar(),null);const s=ejemplo();s.entorno='beta';p.aplicar(s,{cuentaId:A,revision:1});assert.ok(storage.getItem('caoz.coleccion.v1.beta.csm-game-guide%2Ftcg-beta'));assert.equal(JSON.parse(storage.getItem('caoz.coleccion.v1.produccion.raiz')).sobres,4);});
await prueba('Reiniciar confirmado elimina ambos alias pero conserva el vínculo para guardar el reset',()=>{const {p,storage}=entorno({ruta:'/movil'});p.aplicar(ejemplo(),{cuentaId:A,revision:2});p.reiniciar();assert.equal(p.capturar(),null);assert.equal(p.vinculado().revision,2);assert.equal(storage.getItem('caoz.coleccion.v1.produccion.raiz'),null);assert.equal(storage.getItem('caoz.coleccion.v1.produccion.movil'),null);});
await prueba('Un canje real en escritorio no reaparece como cinco Foil al abrir la ruta móvil',()=>{const e=entorno({ruta:'/'});e.ctx.CARDS={tal:{}};e.ctx.LEADERS={};vm.runInContext(fs.readFileSync(new URL('./coleccion-modelo.js',import.meta.url),'utf8'),e.ctx);const s=ejemplo();s.datos.coleccion.cantidades.tal={foil:5};s.datos.coleccion.desbloqueos.tal=['foil'];s.datos.coleccion.pendiente=null;e.p.aplicar(s,{cuentaId:A,revision:1});assert.equal(e.ctx.CAOZ_COLECCION.canjear('tal','foil'),true);const gastado=e.p.capturar();e.p.confirmar(gastado,{cuentaId:A,revision:2});const m=entorno({storage:e.storage,ruta:'/movil'});m.ctx.CARDS={tal:{}};m.ctx.LEADERS={};vm.runInContext(fs.readFileSync(new URL('./coleccion-modelo.js',import.meta.url),'utf8'),m.ctx);assert.equal(m.ctx.CAOZ_COLECCION.clave,'caoz.coleccion.v1.produccion.raiz');assert.equal(m.ctx.CAOZ_COLECCION.cantidad('tal','foil'),0);assert.equal(m.ctx.CAOZ_COLECCION.cantidad('tal','dorado'),1);assert.deepEqual(plano(m.p.capturar()),plano(gastado));});
await prueba('Un login en móvil ya cargado cambia la clave viva de la colección al inventario común',()=>{const e=entorno({ruta:'/movil'});e.ctx.CARDS={tal:{}};e.ctx.LEADERS={};vm.runInContext(fs.readFileSync(new URL('./coleccion-modelo.js',import.meta.url),'utf8'),e.ctx);assert.match(e.ctx.CAOZ_COLECCION.clave,/\.movil$/);e.p.aplicar(ejemplo(),{cuentaId:A,revision:1});assert.equal(e.ctx.CAOZ_COLECCION.clave,'caoz.coleccion.v1.produccion.raiz');});
await prueba('Salir en móvil devuelve la clave del invitado para que sus siguientes cartas sobrevivan a recargar',()=>{const e=entorno({ruta:'/movil'});e.ctx.CARDS={tal:{}};e.ctx.LEADERS={};vm.runInContext(fs.readFileSync(new URL('./coleccion-modelo.js',import.meta.url),'utf8'),e.ctx);e.p.aplicar(ejemplo(),{cuentaId:A,revision:1});e.p.desvincular();assert.equal(e.ctx.CAOZ_COLECCION.clave,'caoz.coleccion.v1.produccion.movil');assert.equal(e.ctx.CAOZ_COLECCION.otorgarCopia('tal','foil'),true);assert.equal(e.p.capturar().datos.coleccion.cantidades.tal.foil,1);const otra=entorno({ruta:'/movil',storage:e.storage});assert.equal(otra.p.capturar().datos.coleccion.cantidades.tal.foil,1);});
await prueba('Una pestaña antigua no puede escribir campaña ni inventario después de cambiar de cuenta',()=>{const e=entorno();e.p.aplicar(ejemplo(),{cuentaId:A,revision:1});e.p.instalarGuardia();let avisos=0;e.eventos.addEventListener('caoz:cuenta-cambio-externo',()=>avisos++);const storageB=new Almacen();storageB.m=e.storage.m;const b=entorno({storage:storageB});b.p.aplicar(ejemplo(),{cuentaId:B,revision:1});assert.throws(()=>e.storage.setItem('caoz.campana.v1','{}'),{codigo:'CUENTA_CAMBIADA'});assert.throws(()=>e.storage.removeItem('caoz.coleccion.v1.produccion.raiz'),{codigo:'CUENTA_CAMBIADA'});e.storage.setItem('caoz.sonido.v1','preferencia');assert.equal(avisos,1);assert.equal(b.p.capturar().datos.coleccion.sobres,4);e.p.destruir();b.p.destruir();});
await prueba('La guardia permite importaciones propias y los autosaves de la misma sesión',()=>{const e=entorno();e.p.instalarGuardia();e.p.aplicar(ejemplo(),{cuentaId:A,revision:1});e.storage.setItem('caoz_nombre','Ari 2');assert.equal(e.p.capturar().datos.nombre,'Ari 2');e.p.confirmar(e.p.capturar(),{cuentaId:A,revision:2});e.storage.setItem('caoz_nombre','Ari 3');assert.equal(e.p.capturar().datos.nombre,'Ari 3');e.p.desvincular();e.storage.setItem('caoz_nombre','Invitado');assert.equal(e.p.capturar().datos.nombre,'Invitado');e.p.destruir();});
await prueba('Cambiar A→B y cerrar sesión invalida la miniatura en memoria sin borrar el borrador importado',()=>{
  const e=entorno(),personaje=fs.readFileSync(new URL('./campana-personaje.js',import.meta.url),'utf8'),final=fs.readFileSync(new URL('./final-core.js',import.meta.url),'utf8');
  const lectura=personaje.slice(0,personaje.indexOf('/* Malla de resina'));
  let refresco=final.slice(final.indexOf('function cuentaRecargarProgreso(){'),final.indexOf('function clavesProgresoLocal(){'));
  if(process.env.CAOZ_SABOTAJE_PROGRESO==='borrador'){const [antes,despues]=mutantes.borrador;assert.ok(refresco.includes(antes));refresco=refresco.replace(antes,despues);}
  e.ctx.LEADERS={mohamed:{n:'Mohamed'},fender:{n:'Fender'}};
  let enMenu=true;e.ctx.document={querySelector:s=>s==='#extras.on,#menu.on'?enMenu:!enMenu};
  vm.runInContext("const CAMPANA_CLAVE='caoz.campana.v1';let campanaMemoria=null,campanaEnsayoGero=null,RECORD_ULTIMO=null;"+lectura+refresco,e.ctx);
  e.eventos.addEventListener('caoz:cuenta-importada',()=>e.ctx.cuentaRecargarProgreso());
  const a=ejemplo();a.datos.borrador={personaje:{nombre:'Personaje A',color:'verde',equipo:'libro'},lider:'fender'};
  e.p.aplicar(a,{cuentaId:A,revision:1});assert.equal(e.ctx.campanaLeerBorrador().personaje.nombre,'Personaje A');
  const b=ejemplo();b.datos.borrador={personaje:{nombre:'Personaje B',color:'azul',equipo:'baston'},lider:'mohamed'};
  e.p.aplicar(b,{cuentaId:B,revision:1});const antes=e.storage.getItem('caoz.campana.v1.creador');
  assert.equal(e.ctx.campanaLeerBorrador().personaje.nombre,'Personaje B');assert.equal(e.ctx.campanaLeerBorrador().personaje.color,'azul');assert.equal(e.ctx.campanaLeerBorrador().lider,'mohamed');
  assert.equal(e.storage.getItem('caoz.campana.v1.creador'),antes);e.ctx.campanaGuardarBorrador();assert.equal(JSON.parse(e.storage.getItem('caoz.campana.v1.creador')).personaje.nombre,'Personaje B');
  enMenu=false;const vivo=e.ctx.campanaLeerBorrador();assert.equal(e.ctx.cuentaRecargarProgreso(),false);assert.equal(vm.runInContext('campanaBorrador',e.ctx),vivo);
  enMenu=true;e.p.desvincular();assert.equal(e.ctx.campanaLeerBorrador().personaje.nombre,'Viajero');e.ctx.campanaGuardarBorrador();assert.equal(JSON.parse(e.storage.getItem('caoz.campana.v1.creador')).personaje.nombre,'Viajero');e.p.destruir();
});
console.log(`${total} pruebas del adaptador de progreso aprobadas.`);
if(process.argv.includes('--sabotaje')&&!process.env.CAOZ_SABOTAJE_PROGRESO){
  for(const nombre of Object.keys(mutantes)){const r=spawnSync(process.execPath,[fileURLToPath(import.meta.url)],{env:{...process.env,CAOZ_SABOTAJE_PROGRESO:nombre},encoding:'utf8'});
    assert.notEqual(r.status,0,'El sabotaje '+nombre+' debe romper una regresión');assert.match(r.stderr,/AssertionError/);console.log('✓ Sabotaje detectado: '+nombre);}
}
