/* Pantalla superior: geometría real reducida y esqueletos animados en la GPU. */
#include "dibujo.hpp"
#include <3ds.h>
#include <citro3d.h>
#include <cstdio>
#include <cstring>
#include <algorithm>
#include "vshader_shbin.h"
namespace Grietas {
struct Vert {float x,y,z,r,g,b,nx,ny,nz,hueso;};
struct Modelo {uint32_t nv=0,ni=0,nh=0,nc=0,nf=0;Vert* vertices=nullptr;u16* indices=nullptr;std::vector<float> poses;};
static Modelo modelos[12];static C3D_RenderTarget* target;static DVLB_s* shader;static shaderProgram_s programa;static int uProy,uModelo,uHuesos,uTinte;static C3D_Mtx vistaProy;static Vert* dinamico;static size_t cursorDinamico=0;static std::vector<Vert> temporal;static Modelo piso;static float camX=0,camZ=4;
static const char*nombres[]={"adreida","mohamed","goblin","kobold","saqueador","can","troll","cobrador","entramada","piedra","taberna","pozo"};
static bool leer(Modelo&m,const char*nombre){char p[128];std::snprintf(p,sizeof(p),"romfs:/%s.bin",nombre);FILE*f=std::fopen(p,"rb");if(!f)return false;uint32_t cab[6];bool ok=fread(cab,4,6,f)==6&&cab[0]==0x33475241&&cab[1]<100000&&cab[2]<200000&&cab[3]>0&&cab[3]<=24&&cab[4]<=16&&cab[5]<=48;if(!ok){fclose(f);return false;}m.nv=cab[1];m.ni=cab[2];m.nh=cab[3];m.nc=cab[4];m.nf=cab[5];m.vertices=(Vert*)linearAlloc(m.nv*sizeof(Vert));size_t ib=(m.ni*2+3)&~3;if(ib)m.indices=(u16*)linearAlloc(ib);if(!m.vertices||(ib&&!m.indices)){fclose(f);return false;}ok=fread(m.vertices,sizeof(Vert),m.nv,f)==m.nv;if(ib)ok&=fread(m.indices,1,ib,f)==ib;m.poses.resize(m.nh*12*m.nc*m.nf);ok&=fread(m.poses.data(),4,m.poses.size(),f)==m.poses.size();fclose(f);return ok;}
static void vert(float x,float y,float z,uint32_t c,float nx=0,float ny=1,float nz=0){temporal.push_back({x,y,z,((c>>16)&255)/255.f,((c>>8)&255)/255.f,(c&255)/255.f,nx,ny,nz,0});}
static void triangulo(float ax,float ay,float az,float bx,float by,float bz,float cx,float cy,float cz,uint32_t col){float ux=bx-ax,uy=by-ay,uz=bz-az,vx=cx-ax,vy=cy-ay,vz=cz-az,nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,l=std::sqrt(nx*nx+ny*ny+nz*nz);if(l<.00001f)return;nx/=l;ny/=l;nz/=l;vert(ax,ay,az,col,nx,ny,nz);vert(bx,by,bz,col,nx,ny,nz);vert(cx,cy,cz,col,nx,ny,nz);}
static void caja(float x,float y,float z,float w,float h,float d,uint32_t c){float X[]={x-w/2,x+w/2},Y[]={y,y+h},Z[]={z-d/2,z+d/2};float v[8][3];for(int i=0;i<8;i++){v[i][0]=X[i&1];v[i][1]=Y[(i>>1)&1];v[i][2]=Z[(i>>2)&1];}const int caras[][4]={{0,4,6,2},{1,3,7,5},{0,1,5,4},{2,6,7,3},{0,2,3,1},{4,5,7,6}};for(auto&f:caras)for(int k=0;k<2;k++){auto&a=v[f[0]];auto&b=v[f[k+1]];auto&c2=v[f[k+2]];triangulo(a[0],a[1],a[2],b[0],b[1],b[2],c2[0],c2[1],c2[2],c);}}
static void abanico(V p,float y,float radio,float dir,float apertura,uint32_t color){int n=std::max(3,(int)(apertura*10));for(int i=0;i<n;i++){V a=p+frente(dir-apertura+2*apertura*i/n)*radio,b=p+frente(dir-apertura+2*apertura*(i+1)/n)*radio;triangulo(p.x,y,p.z,a.x,y,a.z,b.x,y,b.z,color);}}
static void aro(V p,float y,float radio,float ancho,uint32_t color){for(int i=0;i<28;i++){float a=i*TAU/28,b=(i+1)*TAU/28;V p0=p+frente(a)*radio,p1=p+frente(b)*radio,p2=p+frente(b)*(radio-ancho),p3=p+frente(a)*(radio-ancho);triangulo(p0.x,y,p0.z,p1.x,y,p1.z,p2.x,y,p2.z,color);triangulo(p0.x,y,p0.z,p2.x,y,p2.z,p3.x,y,p3.z,color);}}
static void identidadHueso(){C3D_Mtx m;Mtx_Identity(&m);C3D_FVUnifMtx3x4(GPU_VERTEX_SHADER,uHuesos,&m);}
static void transformar(V p,float y,float dir,float escala=1){C3D_Mtx m;Mtx_Identity(&m);Mtx_Translate(&m,p.x,y,p.z,true);Mtx_RotateY(&m,dir,true);Mtx_Scale(&m,escala,escala,escala);C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER,uModelo,&m);}
static void enviar(Vert*v,int n,u16*indices=nullptr,int ni=0){C3D_BufInfo*buf=C3D_GetBufInfo();BufInfo_Init(buf);BufInfo_Add(buf,v,sizeof(Vert),4,0x3210);if(ni)C3D_DrawElements(GPU_TRIANGLES,ni,C3D_UNSIGNED_SHORT,indices);else C3D_DrawArrays(GPU_TRIANGLES,0,n);}
static void objeto(int tipo,V p,float y,float dir,float alpha=1){Modelo&m=modelos[tipo];identidadHueso();transformar(p,y,dir);C3D_FVUnifSet(GPU_VERTEX_SHADER,uTinte,1,1,1,alpha);enviar(m.vertices,m.nv,m.indices,m.ni);}
static void actor(const Actor&a,float y,float transparencia=1){Modelo&m=modelos[a.tipo];int clip=std::max(0,std::min((int)m.nc-1,a.anim));float frame=limite(a.k,0,1)*(m.nf-1);int f=(int)frame,g=std::min((int)m.nf-1,f+1);float mezcla=frame-f;auto*dst=(float*)C3D_FVUnifWritePtr(GPU_VERTEX_SHADER,uHuesos,m.nh*3);int tam=m.nh*12;const float*A=m.poses.data()+(clip*m.nf+f)*tam,*B=m.poses.data()+(clip*m.nf+g)*tam;for(int j=0;j<tam;j++)dst[j]=A[j]+(B[j]-A[j])*mezcla;
 transformar(a.p,y,a.dir);float fade=a.estado==CAIDO?limite((2.5f-a.t)/.8f,0,1):1;float flash=a.flash>0?.5f:0;C3D_FVUnifSet(GPU_VERTEX_SHADER,uTinte,1+flash,1+flash*.5f,1,fade*transparencia);enviar(m.vertices,m.nv,m.indices,m.ni);}
static void lote(float alpha=1){if(temporal.empty())return;size_t n=std::min<size_t>(temporal.size(),30000-cursorDinamico);n-=n%3;Vert* segmento=dinamico+cursorDinamico;std::memcpy(segmento,temporal.data(),n*sizeof(Vert));GSPGPU_FlushDataCache(segmento,n*sizeof(Vert));cursorDinamico+=n;identidadHueso();transformar({},0,0);C3D_FVUnifSet(GPU_VERTEX_SHADER,uTinte,1,1,1,alpha);enviar(segmento,n);temporal.clear();}
bool iniciarDibujo(){shader=DVLB_ParseFile((u32*)vshader_shbin,vshader_shbin_size);if(!shader)return false;shaderProgramInit(&programa);shaderProgramSetVsh(&programa,&shader->DVLE[0]);C3D_BindProgram(&programa);uProy=shaderInstanceGetUniformLocation(programa.vertexShader,"proyeccion");uModelo=shaderInstanceGetUniformLocation(programa.vertexShader,"modelo");uHuesos=shaderInstanceGetUniformLocation(programa.vertexShader,"huesos");uTinte=shaderInstanceGetUniformLocation(programa.vertexShader,"tinte");if(uHuesos<0||uHuesos+72>96)return false;
 auto*a=C3D_GetAttrInfo();AttrInfo_Init(a);AttrInfo_AddLoader(a,0,GPU_FLOAT,3);AttrInfo_AddLoader(a,1,GPU_FLOAT,3);AttrInfo_AddLoader(a,2,GPU_FLOAT,3);AttrInfo_AddLoader(a,3,GPU_FLOAT,1);auto*env=C3D_GetTexEnv(0);C3D_TexEnvInit(env);C3D_TexEnvSrc(env,C3D_Both,GPU_PRIMARY_COLOR,GPU_PRIMARY_COLOR,GPU_PRIMARY_COLOR);C3D_TexEnvFunc(env,C3D_Both,GPU_REPLACE);
 C3D_CullFace(GPU_CULL_NONE);C3D_DepthTest(true,GPU_GREATER,GPU_WRITE_ALL);C3D_AlphaBlend(GPU_BLEND_ADD,GPU_BLEND_ADD,GPU_SRC_ALPHA,GPU_ONE_MINUS_SRC_ALPHA,GPU_ONE,GPU_ONE_MINUS_SRC_ALPHA);
 target=C3D_RenderTargetCreate(240,400,GPU_RB_RGBA8,GPU_RB_DEPTH24_STENCIL8);if(!target)return false;C3D_RenderTargetSetOutput(target,GFX_TOP,GFX_LEFT,GX_TRANSFER_FLIP_VERT(0)|GX_TRANSFER_OUT_TILED(0)|GX_TRANSFER_RAW_COPY(0)|GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8)|GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8)|GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO));
 dinamico=(Vert*)linearAlloc(30000*sizeof(Vert));if(!dinamico)return false;for(int i=0;i<12;i++)if(!leer(modelos[i],nombres[i]))return false;
 // Adoquines de color y juntas oscuras: sin sombreadores PBR ni posprocesado.
 for(int z=-29;z<29;z++)for(int x=-29;x<29;x++){float d=((x*73+z*31)&15)/255.f;uint32_t c=((int)(87+d*255)<<16)|((int)(88+d*230)<<8)|(int)(86+d*210);float X=x+((z&1)? .45f:0);triangulo(X,0,z,X+.96f,0,z,X+.96f,0,z+.96f,c);triangulo(X,0,z,X+.96f,0,z+.96f,X,0,z+.96f,c);}
 piso.nv=temporal.size();piso.vertices=(Vert*)linearAlloc(piso.nv*sizeof(Vert));if(!piso.vertices)return false;std::memcpy(piso.vertices,temporal.data(),piso.nv*sizeof(Vert));temporal.clear();return true;}
void dibujar(Juego&j){C3D_FrameBegin(C3D_FRAME_SYNCDRAW);cursorDinamico=0;std::vector<int> ocultas;C3D_RenderTargetClear(target,C3D_CLEAR_ALL,0x1d293aff,0);C3D_FrameDrawOn(target);C3D_BindProgram(&programa);C3D_Mtx proy,vista;
 camX+=(j.h.p.x-camX)*.12f;camZ+=(j.h.p.z-camZ)*.12f;float shake=std::sin(j.tiempo*53)*j.sacudida*.3f;Mtx_PerspTilt(&proy,32*PI/180,400.f/240,.2f,90,false);Mtx_LookAt(&vista,FVec3_New(camX+shake,17,camZ+13),FVec3_New(camX,.7f,camZ),FVec3_New(0,1,0),false);Mtx_Multiply(&vistaProy,&proy,&vista);C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER,uProy,&vistaProy);
 identidadHueso();transformar({},0,0);C3D_FVUnifSet(GPU_VERTEX_SHADER,uTinte,1,1,1,1);enviar(piso.vertices,piso.nv);
 // Casas: las cercanas delante del héroe dejan ver su posición.
 for(int i=0;i<15;i++){float a=i*TAU/15;bool puerta=false;for(float c:{-PI/2,PI/6,PI*5/6})if(std::fabs(delta(a,c))<.3f)puerta=true;if(puerta)continue;V p{std::cos(a)*19.2f,std::sin(a)*19.2f};if(distancia(p,j.h.p)>24)continue;float alpha=p.z>j.h.p.z&&p.z-j.h.p.z<8&&std::fabs(p.x-j.h.p.x)<3?.22f:1;if(alpha<1)ocultas.push_back(i);else objeto(8+i%3,p,0,angulo(p*-1),1);}
 objeto(11,{-5,-3},0,.27f);
 for(int i=0;i<48;i++){float a=i*TAU/48;V p{std::cos(a)*26.5f,std::sin(a)*26.5f};bool puerta=false;for(float c:{-PI/2,PI/6,PI*5/6})if(std::fabs(delta(a,c))<.09f)puerta=true;if(distancia(p,j.h.p)>25)continue;if(!puerta)caja(p.x,0,p.z,3.5f,3.4f,1.2f,0x6f756e);else{caja(p.x,3.7f,p.z,4,1,1.2f,0x82765f);caja(p.x,0,p.z,.08f,3.7f,.08f,0xffbc56);}}
 for(V p:std::array<V,2>{{{-3.5f,7.5f},{4.5f,-10}}}){caja(p.x,0,p.z,.38f,.2f,.38f,0x79746a);caja(p.x,.2f,p.z,.12f,1.8f,.12f,0x45474b);caja(p.x,2,p.z,.42f,.6f,.42f,0xffc45b);caja(p.x,2.6f,p.z,.56f,.15f,.56f,0x9a7448);}
 caja(6.5f,0,-5.5f,2.5f,.7f,1.4f,0x66503b);caja(8.5f,0,4.8f,1.1f,1.2f,1.1f,0x6c4e36);lote();
 // Sombras baratas bajo los personajes.
 for(const auto&e:j.enemigos){if(distancia(e.p,j.h.p)<19)abanico(e.p,.015f,e.tipo==TROLL?.9f:.4f,0,PI,0x1e2428);}
 abanico(j.h.p,.015f,.5f,0,PI,0x1e2428);lote(.6f);
 for(const auto&e:j.enemigos){if(e.estado!=PREPARA)continue;float radio=e.tipo==CAN?4.6f:e.tipo==TROLL?3.8f:e.tipo==ESCUDO?2.5f:2;float dur=e.tipo==CAN?(e.combo?.55f:1.05f):e.tipo==TROLL?(e.segunda?1.105f:1.3f):e.tipo==KOBOLD?1.1f:.85f;uint32_t c=dur-e.t<.18f?0xbdf5ff:0xe8a15e;
  if(e.tipo==KOBOLD){V b=e.p+frente(e.dir)*11;triangulo(e.p.x,.035f,e.p.z,b.x+.12f,.035f,b.z,b.x-.12f,.035f,b.z,c);}else if(e.tipo==TROLL&&e.numero%3==1)abanico(e.p,.035f,3.5f,0,PI,0xa882c9);else if(e.tipo==CAN&&e.combo==1){abanico(e.p,.035f,radio,e.dir-PI/3,PI/6,c);abanico(e.p,.035f,radio,e.dir+PI/3,PI/6,c);}else abanico(e.p,.035f,radio,e.dir,e.tipo==CAN?PI/6:1.1f,c);
 }for(const auto&p:j.proyectiles)if(p.tipo)aro(p.destino,.04f,p.radio,.07f,p.dur-p.t<.25f?0xc5ffff:p.dur-p.t<.55f?0xffdc55:0xec8049);lote(.38f);
 for(const auto&e:j.efectos){float k=e.t/e.dur;if(e.tipo==4){abanico(e.p,.021f,e.radio*std::fmin(1.f,(e.dur-e.t)/.4f),0,PI,0x191717);aro(e.p,.06f,e.radio,.1f,0x857364);}else if(e.tipo==5)caja(e.p.x,std::sin(k*PI)*1.5f,e.p.z,e.radio,e.radio,e.radio,e.color);else aro(e.p,.1f,e.radio*(.4f+k*.6f),.07f,e.color);}lote(.8f);
 for(const auto&e:j.enemigos){if(distancia(e.p,j.h.p)<20)actor(e,0);}
 actor(j.h,j.alto(j.h),j.h.tipo==MOHAMED&&j.ultiActivo>0?.3f:1);if(j.tieneAliado)actor(j.aliado,0,.6f);
 for(const auto&p:j.proyectiles){if(p.tipo==2){Actor a;a.tipo=COBRADOR;a.p=p.p;a.anim=DOLOR;a.k=.5f;a.dir=j.tiempo*5;actor(a,p.alto);}else if(p.tipo==1)caja(p.p.x,p.alto,p.p.z,.45f,.4f,.45f,0x9a9181);else{V d=unidad(p.vel),b=p.p-d*.65f;triangulo(p.p.x,1.05f,p.p.z,b.x+d.z*.1f,1.05f,b.z-d.x*.1f,b.x-d.z*.1f,1.05f,b.z+d.x*.1f,p.enemigo?0xffad50:0xd4e9ff);}}
 for(const auto&o:j.objetos){if(o.tipo==1)caja(o.p.x,.25f,o.p.z,.35f,.5f,.09f,0xc5a369);else{caja(o.p.x,.1f,o.p.z,.25f,.32f,.25f,0xb54445);caja(o.p.x,.42f,o.p.z,.1f,.09f,.1f,0xd9b981);}}lote();C3D_DepthTest(true,GPU_GREATER,GPU_WRITE_COLOR);for(int i:ocultas){float a=i*TAU/15;V p{std::cos(a)*19.2f,std::sin(a)*19.2f};objeto(8+i%3,p,0,angulo(p*-1),.22f);}C3D_DepthTest(true,GPU_GREATER,GPU_WRITE_ALL);C3D_FrameEnd(0);}
void cerrarDibujo(){for(auto&m:modelos){if(m.vertices)linearFree(m.vertices);if(m.indices)linearFree(m.indices);}if(piso.vertices)linearFree(piso.vertices);if(dinamico)linearFree(dinamico);if(target)C3D_RenderTargetDelete(target);shaderProgramFree(&programa);if(shader)DVLB_Free(shader);}
}
